version: "3.1"

services:
    media-center:
        build:
            context: .
        restart: always
        environment:
            NODE_ENV: production
        ports:
            - "3000:3000"
        volumes:
            - ./db.json:/app/db.json
