version: "3.1"

services:
    media-center-prod:
        build:
            context: .
        restart: always
        profiles:
            - prod
        environment:
            NODE_ENV: production
            SERVER_DB_PATH: data/db.json
        ports:
            - "3000:3000"
        volumes:
            - ./data/db.json:/app/data/db.json

    media-center-dev:
        build:
            context: .
        profiles:
            - dev
        environment:
            NODE_ENV: development
            SERVER_DB_PATH: data/db.json
        ports:
            - "3000:3000"
        volumes:
            - ${PWD}/data/db.json:/app/data/db.json
